Initial pass as supporting ngraph_dist builds with both gcc and clang.  Includes deprecated targets to support Jenkins CI with old feature and development branches that may not have these changes.

diff --git a/contrib/docker/Makefile b/contrib/docker/Makefile
--- a/contrib/docker/Makefile
+++ b/contrib/docker/Makefile
@@ -23,8 +23,14 @@ DOCKUSER_HOME=/home/dockuser
 # /root/ngraph-cpp-test is not used, because /root is not accessible to user
 VOLUME = -v "${DIR}:${DOCKUSER_HOME}/ngraph-cpp-test"
 GIT_COMMIT = $(shell git rev-parse HEAD)
-BUILD_VERSION = ${GIT_COMMIT}_${PYTHON_VERSION}
-BUILD_DIR = ${DIR}/contrib/docker/.build-${BUILD_VERSION}
+DBUILD_VERSION = ${GIT_COMMIT}_${PYTHON_VERSION}
+DBUILD_DIR = ${DIR}/contrib/docker/.build-${DBUILD_VERSION}
+
+# For gcc builds, we do NOT regard warnings as errors
+# For clang builds, we DO make warnings into errors
+CMAKE_OPTIONS_COMMON=-DNGRAPH_BUILD_DOXYGEN_DOCS=ON -DNGRAPH_BUILD_SPHINX_DOCS=ON
+CMAKE_OPTIONS_GCC=$CMAKE_OPTIONS_COMMON -DNGRAPH_INSTALL_PREFIX=${DOCKUSER_HOME}/ngraph-cpp-test/BUILD-GCC/ngraph_dist
+CMAKE_OPTIONS_CLANG=$CMAKE_OPTIONS_COMMON -DNGRAPH_INSTALL_PREFIX=${DOCKUSER_HOME}/ngraph-cpp-test/BUILD-CLANG/ngraph_dist -DCMAKE_CXX_COMPILER=clang++-3.9 -DCMAKE_C_COMPILER=clang-3.9 -DNGRAPH_WARNINGS_AS_ERRORS=ON
 
 CALLER_UID := $(shell id -u)
 CALLER_GID := $(shell id -g)
@@ -33,7 +39,10 @@ CALLER_GID := $(shell id -g)
 # line
 PYTHON_VERSION = 2
 
-.PHONY: clean build_ngraph_cpp_cpu check_cpu install shell build_all
+# Some targets are DEPRECATED and will be removed at a later date: check_cpu build_ngraph_cpp_cpu
+# These DEPRECATED targets are currently included for Jenkins job compatibility with older dev branches
+# Please see comments for individual targets for more details
+.PHONY: clean build_docker_ngraph_cpp build_gcc check_gcc build_clang check_clang install_gcc install_clang shell check_cpu build_all build_ngraph_cpp_cpu
 
 DOCKER_BUILD=docker build --rm=true
 
@@ -47,58 +56,107 @@ DOCKER_BUILD+=--build-arg https_proxy=$(https_proxy)
 DOCKER_RUN_ENV+=--env "https_proxy=$(https_proxy)"
 endif
 
+all: check_gcc check_clang
+
 expand_dockerfile_templates:
 	cd "${DIR}"/contrib/docker
-	mkdir "${BUILD_DIR}" || true
-	sed -e 's/\(FROM ngraph.*\)/\1:${BUILD_VERSION}/' Dockerfile.ngraph_cpp_cpu > "${BUILD_DIR}"/Dockerfile.ngraph_cpp_cpu
+	mkdir "${DBUILD_DIR}" || true
+	sed -e 's/\(FROM ngraph.*\)/\1:${DBUILD_VERSION}/' Dockerfile.ngraph_cpp > "${DBUILD_DIR}"/Dockerfile.ngraph_cpp
 
 clean:
 	rm -f "${DIR}"/contrib/docker/.build-*/Dockerfile.* || echo "keep going if files are not present"
 	rmdir "${DIR}"/contrib/docker/.build-* || echo "keep going if directory is not present"
-	rm -fr "${DIR}"/BUILD
+	rm -fr "${DIR}"/BUILD-GCC
+	rm -fr "${DIR}"/BUILD-CLANG
 
-build_ngraph_cpp_cpu: expand_dockerfile_templates
-	$(DOCKER_BUILD) -f="${BUILD_DIR}"/Dockerfile.ngraph_cpp_cpu --build-arg python_version="${PYTHON_VERSION}" -t=ngraph_cpp_cpu:"${BUILD_VERSION}" "${DIR}"
+build_docker_ngraph_cpp: expand_dockerfile_templates
+	$(DOCKER_BUILD) -f="${DBUILD_DIR}"/Dockerfile.ngraph_cpp --build-arg python_version="${PYTHON_VERSION}" -t=ngraph_cpp:"${DBUILD_VERSION}" "${DIR}"
 	# remove the tag for the previous latest image
-	docker rmi ngraph_cpp_cpu:latest || echo "keep going if docker rmi command fails"
-	docker tag `docker images -q "ngraph_cpp_cpu:${BUILD_VERSION}"` ngraph_cpp_cpu:latest
+	docker rmi ngraph_cpp:latest || echo "keep going if docker rmi command fails"
+	docker tag `docker images -q "ngraph_cpp:${DBUILD_VERSION}"` ngraph_cpp:latest
 
-build_all: build_ngraph_cpp_cpu
+build_docker: build_docker_ngraph_cpp
 
-check_cpu: build_ngraph_cpp_cpu
+build_gcc: build_docker_ngraph_cpp
 	# Remove old distribution directory if present
-	( test -d "${DIR}"/BUILD/ngraph_dist && rm -fr "${DIR}"/BUILD/ngraph_dist && echo "Removed old ${DIR}/BUILD/ngraph_dist directory" ) || echo "Previous ngraph_dist directory not found"
-	# Make BUILD directory as user
-	mkdir -p "${DIR}"/BUILD
-	chmod ug+rwx "${DIR}"/BUILD
+	( test -d "${DIR}"/BUILD-GCC/ngraph_dist && rm -fr "${DIR}"/BUILD-GCC/ngraph_dist && echo "Removed old ${DIR}/BUILD-GCC/ngraph_dist directory" ) || echo "Previous ngraph_dist directory not found"
+	# Make BUILD-GCC directory as user
+	mkdir -p "${DIR}"/BUILD-GCC
+	chmod ug+rwx "${DIR}"/BUILD-GCC
 	docker run --rm --tty \
             ${VOLUME} \
 	    ${DOCKER_RUN_ENV} \
-            --env GTEST_OUTPUT="xml:${DOCKUSER_HOME}/ngraph-cpp-test/BUILD/unit-test-results.xml" \
+            --env GTEST_OUTPUT="xml:${DOCKUSER_HOME}/ngraph-cpp-test/BUILD-GCC/unit-test-results.xml" \
             --env RUN_UID="$(shell id -u)" \
-            --env RUN_CMD="set -e ; set -o pipefail ; cd ${DOCKUSER_HOME}/ngraph-cpp-test/BUILD; cmake -DCMAKE_CXX_COMPILER=clang++-3.9 -DCMAKE_C_COMPILER=clang-3.9 -DNGRAPH_BUILD_DOXYGEN_DOCS=ON -DNGRAPH_BUILD_SPHINX_DOCS=ON -DNGRAPH_WARNINGS_AS_ERRORS=ON .. 2>&1 | tee cmake.log ; env VERBOSE=1 make ${PARALLEL} 2>&1 | tee make.log ; env VERBOSE=1 make check 2>&1 | tee make_check.log" \
-            "ngraph_cpp_cpu:${BUILD_VERSION}" \
+            --env RUN_CMD="set -e ; set -o pipefail ; cd ${DOCKUSER_HOME}/ngraph-cpp-test/BUILD-GCC; cmake ${CMAKE_OPTIONS_GCC} .. 2>&1 | tee cmake.log ; env VERBOSE=1 make ${PARALLEL} 2>&1 | tee make.log ; env VERBOSE=1 make check 2>&1 | tee make_check.log" \
+            "ngraph_cpp:${DBUILD_VERSION}" \
 	    sh -c "${DOCKUSER_HOME}/ngraph-cpp-test/contrib/docker/run_as_user.sh"
 
-shell: build_ngraph_cpp_cpu
+# XXXXX  TEST GCC BUILDS  XXXXX
+
+build_clang: # XXXXX  CREATE CLANG BUILD CHAIN  XXXXX
+	# Remove old distribution directory if present
+	( test -d "${DIR}"/BUILD-CLANG/ngraph_dist && rm -fr "${DIR}"/BUILD-CLANG/ngraph_dist && echo "Removed old ${DIR}/BUILD-CLANG/ngraph_dist directory" ) || echo "Previous ngraph_dist directory not found"
+	# Make BUILD-CLANG directory as user
+	mkdir -p "${DIR}"/BUILD-CLANG
+	chmod ug+rwx "${DIR}"/BUILD-CLANG
+	docker run --rm --tty \
+            ${VOLUME} \
+	    ${DOCKER_RUN_ENV} \
+            --env GTEST_OUTPUT="xml:${DOCKUSER_HOME}/ngraph-cpp-test/BUILD-CLANG/unit-test-results.xml" \
+            --env RUN_UID="$(shell id -u)" \
+            --env RUN_CMD="set -e ; set -o pipefail ; cd ${DOCKUSER_HOME}/ngraph-cpp-test/BUILD-CLANG; cmake ${CMAKE_OPTIONS_CLANG} .. 2>&1 | tee cmake.log ; env VERBOSE=1 make ${PARALLEL} 2>&1 | tee make.log ; env VERBOSE=1 make check 2>&1 | tee make_check.log" \
+            "ngraph_cpp:${DBUILD_VERSION}" \
+	    sh -c "${DOCKUSER_HOME}/ngraph-cpp-test/contrib/docker/run_as_user.sh"
+
+
+#            --env RUN_CMD="set -e ; set -o pipefail ; cd ${DOCKUSER_HOME}/ngraph-cpp-test/BUILD-GCC; cmake -DCMAKE_CXX_COMPILER=clang++-3.9 -DCMAKE_C_COMPILER=clang-3.9 -DNGRAPH_BUILD_DOXYGEN_DOCS=ON -DNGRAPH_BUILD_SPHINX_DOCS=ON -DNGRAPH_WARNINGS_AS_ERRORS=ON .. 2>&1 | tee cmake.log ; env VERBOSE=1 make ${PARALLEL} 2>&1 | tee make.log ; env VERBOSE=1 make check 2>&1 | tee make_check.log" \
+
+
+check_gcc: build_gcc  # XXXXX  Implement split between build and check for gcc
+
+install_gcc: check_gcc
+	# Puts ngraph_dist in BUILD-GCC directory.  This is used by Jenkins ngraph-tensorflow batch job.
+	docker run --rm --tty \
+            ${VOLUME} \
+	    ${DOCKER_RUN_ENV} \
+            --env RUN_UID="$(shell id -u)" \
+            --env RUN_CMD="set -e ; set -o pipefail; cd ${DOCKUSER_HOME}/ngraph-cpp-test/BUILD-GCC ; test -d ngraph_dist && rm -fr ngraph_dist && echo 'Removed old ngraph_dist directory' ; make install 2>&1 | tee make_install_gcc.log ; tar cvzf ngraph_dist_gcc.tgz ngraph_dist 2>&1 | tee make_tarball_gcc.log" \
+            "ngraph_cpp:${DBUILD_VERSION}" \
+	    sh -c "${DOCKUSER_HOME}/ngraph-cpp-test/contrib/docker/run_as_user.sh"
+
+check_clang: build_clang  # XXXXX  Implement split between build and check for clang
+
+install_clang: check_clang  # XXXXX
+	# Puts ngraph_dist in BUILD-CLANG directory.  This is used by Jenkins ngraph-tensorflow batch job.
+	docker run --rm --tty \
+            ${VOLUME} \
+	    ${DOCKER_RUN_ENV} \
+            --env RUN_UID="$(shell id -u)" \
+            --env RUN_CMD="set -e ; set -o pipefail; cd ${DOCKUSER_HOME}/ngraph-cpp-test/BUILD-CLANG ; test -d ngraph_dist && rm -fr ngraph_dist && echo 'Removed old ngraph_dist directory' ; make install 2>&1 | tee make_install_clang.log ; tar cvzf ngraph_dist_clang.tgz ngraph_dist 2>&1 | tee make_tarball_clang.log" \
+            "ngraph_cpp:${DBUILD_VERSION}" \
+	    sh -c "${DOCKUSER_HOME}/ngraph-cpp-test/contrib/docker/run_as_user.sh"
+
+shell: build_docker_ngraph_cpp
 	# "make shell" runs an interactive shell in the docker image, for debugging
 	docker run --rm --tty --interactive \
             ${VOLUME} \
 	    ${DOCKER_RUN_ENV} \
             --env RUN_UID="$(shell id -u)" \
-            "ngraph_cpp_cpu:${BUILD_VERSION}" \
+            "ngraph_cpp:${DBUILD_VERSION}" \
             sh -c "cd ${DOCKUSER_HOME} ; ${DOCKUSER_HOME}/ngraph-cpp-test/contrib/docker/run_as_user.sh"
 
-install:
-	# Puts ngraph_dist in BUILD directory.  This is used by Jenkins ngraph-tensorflow batch job.
-	# Note: We currently have a bug where cmake only installs in $HOME.  Jira NGTF-205 is opened
-	#       for this.  For now, here we install to $HOME, then move the directory.
-	docker run --rm --tty \
-            ${VOLUME} \
-	    ${DOCKER_RUN_ENV} \
-            --env RUN_UID="$(shell id -u)" \
-            --env RUN_CMD="set -e ; set -o pipefail; cd ${DOCKUSER_HOME}/ngraph-cpp-test/BUILD ; test -d ngraph_dist && rm -fr ngraph_dist && echo 'Removed old ngraph_dist directory' ; make install 2>&1 | tee make_install.log ; mv -v ${DOCKUSER_HOME}/ngraph_dist ${DOCKUSER_HOME}/ngraph-cpp-test/BUILD" \
-            "ngraph_cpp_cpu:${BUILD_VERSION}" \
-	    sh -c "${DOCKUSER_HOME}/ngraph-cpp-test/contrib/docker/run_as_user.sh"
+#
+# DEPRECATED TARGETS -- These WILL BE REMOVED in a future revision.
+#                       They exist here to maintain compatibility in Jenkins
+#                       jobs on older development branches.
+#
 
-all: build_ngraph_cpp_cpu
+check_cpu: check_gcc
+	echo 'WARNING: "make check_cpu" is DEPRECATED and will be removed in a future revision'
+
+build_all: check_gcc
+	echo 'WARNING: "make build_all" is DEPRECATED and will be removed in a future revision'
+
+build_ngraph_cpp_cpu: build_docker_ngraph_cpp
+	echo 'WARNING: "make build_ngraph_cpp_cpu" is DEPRECATED and will be removed in a future revision'
